### ISSUE TITLE
Align buttons on the file edit view

### ISSUE THREAD

**Issue by sophiedeziel** [sophiedeziel/Tentacles#31]
![Screen Shot 2022-04-06 at 8 56 25 PM](https://user-images.githubusercontent.com/1037105/162098954-26721206-6c9a-4e3d-b2cd-fad75e2cc914.png)

The Save and the Docs buttons are not aligned. They should be.

**Comment by alireza-jahandoost** [comment]
interested

**Comment by sophiedeziel** [comment]
No longer an issue with #1104
